### ISSUE TITLE
Cannot find module 'linkedin-js' -- probably a problem with NPM install

### ISSUE THREAD

**Issue by paulshapiro** [masylum/linkedin-js#1]
Hi,

Thanks for the libs, I hope I get to use them.

I installed linkedin-js via npm and used similar code to the example, like this,

```
app.get('/linkedin/share/:message', function (req, res) {
  var linkedinClient = require('linkedin-js').linkedinClient( '[redacted]',
  '[redacted]' );

  linkedinClient.getAccessToken(req, res, function (error, token) {
    linkedinClient.apiCall('POST', '/people/~/shares',
      {
        token: token,
        share: {
          comment: message,
          visibility: {code: 'anyone'}
        }
      },
      function (error, result) {

        console.log('err: ' + sys.inspect(error) + ', result: ' + result );

        // res.render('linkedin_share.jade', {locals: {result: result}});
      }
    );
  });
 });    
```

But when I go to this page I get an error in the console that it cannot find the package linkedin-js like this

```
Error: Cannot find module 'linkedin-js'
   at loadModule (node.js:275:15)
   at require (node.js:411:14)
```

   ....

I'll also post this on the npm board if you'd like me to but isaacs usually says to bug the dev.

Thanks man,

Paul.

**Comment by masylum** [comment]
I will check that this weekend. I'm having lots of problems publishing my modules to npm, I'm not sure what I'm doing wrong on my package.json files...
If you want to start trying the module right now, clone the repo and require it manually.

**Comment by paulshapiro** [comment]
Hi, thanks for the reply.

I tried that after your suggestion, but I get what appears to be an oauth error when I try to run it. I am requiring index, I hope that's correct.

Like this,

```
  var linkedinClient = require('./linkedin-js/index').linkedinClient(
                  ...
```

Which results in:

```
/..../node/linkedin-js/lib/linkedin_client.js:127
        req.session.auth.linkedin_oauth_token_secret = oauth_token_secret;
                                                     ^
TypeError: Cannot set property 'linkedin_oauth_token_secret' of undefined
   at /..../node/linkedin-js/lib/linkedin_client.js:127:58
   at /usr/local/lib/node/.npm/oauth/0.8.3/package/lib/oauth.js:349:7
```

Any ideas? oauth is apparently installed according to npm and I don't get any include errors.
Thanks

**Comment by masylum** [comment]
I updated the docs and the module a little bit.
You need to enable the sessions middleware (I forgot to put that on the Readme sorry!).

Try again with npm! Check the Readme example again and tell me if it works.

**Comment by paulshapiro** [comment]
I dunno man, it's not working for me. I reinstalled with npm, got v0.0.2, set up with the new method,

```
  var linkedinClient = require('linkedin-js')(
  '...', '...' );
```

And I am using express' session and cookie decoder like this, becaus app.use() and app.configure() apparently don't exist anymore even though the docs say that it's usable... (?)

```
express.cookieDecoder(),
express.session( { store : mongoStore, port : constants.DBPort } ),
```

I know session is working because i'm using it for login sessions.. but I also tried using connect's exports instead of express', Same thing though.

So still no dice. I basically get the same error about req.session.auth being undefined. 

So I tried to set req.session.auth = new Obect(); before the linkedin calls, and I get this:

```
/usr/local/lib/node/.npm/express/1.0.0rc4/package/lib/express/response.js:339
    var basePath = this.app.set('home') || '/';
                            ^
7 Nov 13:43:20 - [ERROR] TypeError
TypeError: Cannot call method 'set' of undefined
    at ServerResponse.redirect (/usr/local/lib/node/.npm/express/1.0.0rc4/package/lib/express/response.js:339:29)
    at /usr/local/lib/node/.npm/linkedin-js/0.0.2/package/lib/linkedin_client.js:129:17
    at /usr/local/lib/node/.npm/oauth/0.8.3/package/lib/oauth.js:349:7
    at IncomingMessage.<anonymous> (/usr/local/lib/node/.npm/oauth/0.8.3/package/lib/oauth.js:265:11)
    at IncomingMessage.emit (events:41:20)
    at HTTPParser.onMessageComplete (http:107:23)
    at Client.onData [as ondata] (http:848:27)
    at IOWatcher.callback (net:494:29)
    at node.js:768:9
```

It might just be me! But I dunno what's going on.

Thanks for looking into this!

**Comment by masylum** [comment]
I published a new version with some bugs fixed and a test/example
Let me know if it works for you. Thanks.
